// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZtcbIuSRoSsJsttmFhZPKbA8J4tifUfY',
    appId: '1:109427383125:web:a50e30e937e5649a086ddc',
    messagingSenderId: '109427383125',
    projectId: 'indieimprints',
    authDomain: 'indieimprints.firebaseapp.com',
    storageBucket: 'indieimprints.appspot.com',
    measurementId: 'G-TWDZME9F1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQlYF5PUDaZ5ckVANcbmQBP82TY9nyno',
    appId: '1:109427383125:android:4b9101a7f0bc1671086ddc',
    messagingSenderId: '109427383125',
    projectId: 'indieimprints',
    storageBucket: 'indieimprints.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-cTl-0fs4Op09sRcQKcdkTZi_Rb4dmLo',
    appId: '1:109427383125:ios:95797dac6e370691086ddc',
    messagingSenderId: '109427383125',
    projectId: 'indieimprints',
    storageBucket: 'indieimprints.appspot.com',
    androidClientId: '109427383125-u5h5iebvin04eog4i4a4d5a2v0qi6mkt.apps.googleusercontent.com',
    iosClientId: '109427383125-fkje40mo93147tvpnc6vb0rqb9hlmru7.apps.googleusercontent.com',
    iosBundleId: 'com.eyecreality.indieimprint',
  );

  static const FirebaseOptions iosflatline = FirebaseOptions(
    apiKey: 'AIzaSyC-cTl-0fs4Op09sRcQKcdkTZi_Rb4dmLo',
    appId: '1:109427383125:ios:95797dac6e370691086ddc',
    messagingSenderId: '109427383125',
    projectId: 'indieimprints',
    storageBucket: 'indieimprints.appspot.com',
    androidClientId: '109427383125-u5h5iebvin04eog4i4a4d5a2v0qi6mkt.apps.googleusercontent.com',
    iosClientId: '109427383125-fkje40mo93147tvpnc6vb0rqb9hlmru7.apps.googleusercontent.com',
    iosBundleId: 'com.eyecreality.indieimprints.flatlinecomics',
  );
}
